### ISSUE TITLE
How to generate and upload docs to github pages?

### ISSUE THREAD

**Issue by jorgecarleitao** [vemel/handsdown#20]
Thanks a lot for this repo!

It seems that this package generates the docs with the intention of committing them to git. Is that the idea? 

Is there a way to generate the docs and upload them to github instead (i.e. not commit them to git) - it is usually an anti-pattern to store generated content in git since it innevitably leads to a drift between that content and the code (e.g. folks forget to update the auto-docs).

Thanks

**Comment by vemel** [comment]
Hello!

You are right, generated docs should be uploaded to GitHub ideally. And you have to store them in Git anyway. 

Possible solutions:
- setup a `pre-commit` hook to regenerate docs before commit (be ready to face potential conflicts if multiple people work on the same project)
- store docs in a separate `gh-pages` branch. You can set up a GitHub Actions workflow to update docs on PR merged to `main`. Please let me know if you need additional info on this approach
- store docs in a separate repo. Can also be done automatically with GH Actions on PR merge. The approach is almost identical to the previous, just push to another repo. You might need to add your GH token to secrets in order to do this

Please let me know if any of these approaches work for you

**Comment by vemel** [comment]
Example `.github/workflows/update_docs.yml` workflow:

```yaml
name: Update docs

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U poetry pip
          poetry config virtualenvs.create false
          poetry install -n
      - name: Switch to docs branch
        run: |
          git checkout gh-pages
          git merge main
      - name: Build docs
        run: |
          python -o docs -m module_name --external `git config --get remote.origin.url` --cleanup --branch main $@
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -am "Update docs"
          git push
```

- Create `GITHUB_TOKEN ` secret
- Create `gh-pages` branch: `git checkout -b gh-pages && git push`
- Change `module_name` to your module name
- I assume you use poetry. Change `Install dependencies` step otherwise
